CREATE TABLE FN
(NM VARCHAR2(40));

INSERT ALL
INTO FN(NM)VALUES('GANESH MAHADEV KAVHAR')
INTO FN(NM)VALUES('HARI JSJJD KAVHAR')
SELECT * FROM DUAL;

SELECT * FROM FN;

--FIRST NAME 
SELECT NM,SUBSTR(NM,1,INSTR(NM,' ',1,1)-1) AS first
FROM FN;

--MIDDLE NAME 
SELECT NM,
SUBSTR(NM,INSTR(NM,' ',1,1)+1, INSTR(NM,' ',1,2)-INSTR(NM,' ',1,1)-1) AS middle
FROM FN;

--LAST NAME 
SELECT NM,SUBSTR(NM,INSTR(NM,' ',1,2)+1) AS LN
FROM FN;
